rbs = ["Jonathan Taylor",
"Christian McCaffrey",
"Austin Ekeler",
"Najee Harris",
"Derrick Henry",
"Dalvin Cook",
"Joe Mixon",
"D'Andre Swift",
"Leonard Fournette",
"Aaron Jones",
"Alvin Kamara",
"James Conner",
"Nick Chubb",
"Cam Akers",
"Saquon Barkley",
"Javonte Williams",
"David Montgomery",
"Ezekiel Elliott",
"Breece Hall",
"Antonio Gibson",
"AJ Dillon",
"Travis Etienne",
"J.K. Dobbins",
"Josh Jacobs",
"Miles Sanders",
"Elijah Mitchell",
"Clyde Edwards-Helaire",
"Chase Edmonds",
"Damien Harris",
"Ken Walker",
"Rhamondre Stevenson",
"Rashaad Penny",
"Tony Pollard",
"Kareem Hunt",
"Cordarrelle Patterson",
"Devin Singletary",
"Dameon Pierce",
"Melvin Gordon",
"Nyheim Hines"]

wrs = ["Cooper Kupp",
"Ja'Marr Chase",
"Justin Jefferson",
"Davante Adams",
"Stefon Diggs",
"CeeDee Lamb",
"Deebo Samuel",
"Tyreek Hill",
"Mike Evans",
"Tee Higgins",
"A.J. Brown",
"DJ Moore",
"Michael Pittman Jr",
"Keenan Allen",
"Diontae Johnson",
"Mike Williams",
"Amari Cooper",
"DK Metcalf",
"Jaylen Waddle",
"Brandin Cooks",
"Terry McLaurin",
"Allen Robinson",
"Marquise Brown",
"Chris Godwin",
"Courtland Sutton",
"Rashod Bateman",
"Gabriel Davis",
"Jerry Jeudy",
"Elijah Moore",
"Michael Thomas",
"Darnell Mooney",
"Amon-Ra St. Brown",
"DeVonta Smith",
"JuJu Smith-Schuster",
"Brandon Aiyuk",
"Allen Lazard",
"Tyler Lockett",
"Drake London"]


full_list = ['Jonathan Taylor',
'Austin Ekeler',
'Christian McCaffrey',
'Cooper Kupp',
'Justin Jefferson',
'Dalvin Cook',
'Najee Harris',
'Derrick Henry',
'Ja\'Marr Chase',
'Joe Mixon',
'CeeDee Lamb',
'D\'Andre Swift',
'Leonard Fournette',
'Davante Adams',
'Stefon Diggs',
'Aaron Jones',
'Alvin Kamara',
'Javonte Williams',
'Saquon Barkley',
'Mike Evans',
'Nick Chubb',
'Deebo Samuel',
'A.J. Brown',
'Keenan Allen',
'James Conner',
'Michael Pittman Jr.',
'Tyreek Hill',
'DJ Moore',
'Ezekiel Elliott',
'Tee Higgins',
'David Montgomery',
'Breece Hall',
'Diontae Johnson',
'Jaylen Waddle',
'Cam Akers',
'AJ Dillon',
'Mike Williams',
'Courtland Sutton',
'Darnell Mooney',
'Antonio Gibson',
'DK Metcalf',
'Terry McLaurin',
'Travis Etienne Jr.',
'Brandin Cooks',
'Elijah Mitchell',
'J.K. Dobbins',
'Allen Robinson II',
'Amari Cooper',
'Josh Jacobs',
'Marquise Brown',
'Jerry Jeudy',
'Chris Godwin',
'Elijah Moore',
'Rashod Bateman',
'Clyde Edwards-Helaire',
'JuJu Smith-Schuster',
'Tony Pollard',
'Michael Thomas',
'Miles Sanders',
'Amon-Ra St. Brown',
'Devin Singletary',
'Melvin Gordon III',
'Chase Edmonds',
'Gabriel Davis',
'Kareem Hunt',
'Cordarrelle Patterson',
'Damien Harris',
'Tyler Lockett',
'Ken Walker III',
'Rashaad Penny',
'Drake London',
'Rhamondre Stevenson',
'DeVonta Smith',
'Adam Thielen',
'James Cook',
'Allen Lazard',
'Christian Kirk',
'Treylon Burks',
'Brandon Aiyuk',
'Michael Carter',
'Garrett Wilson',
'Hunter Renfrow',
'DeAndre Hopkins',
'Kadarius Toney',
'Alexander Mattison',
'Russell Gage',
'Dameon Pierce',
'Robert Woods',
'Ronald Jones II',
'Darrell Henderson Jr.',
'Chris Olave',
'Jakobi Meyers',
'Chase Claypool',
'Skyy Moore',
'J.D. McKissic',
'Marquez Valdes-Scantling',
'Jarvis Landry',
'Michael Gallup',
'Tyler Boyd',
'Kenneth Gainwell',
'James Robinson',
'Isaiah Spiller',
'Tyler Allgeier',
'Nyheim Hines',
'DJ Chark Jr.',
'Sony Michel',
'Darrel Williams',
'Khalil Herbert',
'Van Jefferson',
'Christian Watson',
'Rachaad White',
'Marlon Mack',
'Kenny Golladay',
'Corey Davis',
'DeVante Parker',
'Raheem Mostert',
'Mark Ingram II',
'Gus Edwards',
'George Pickens',
'Rondale Moore',
'Jamison Crowder',
'Jalen Tolbert',
'Jameson Williams',
'D\'Onta Foreman',
'Nico Collins',
'K.J. Osborn',
'D\'Ernest Johnson',
'Julio Jones',
'Zamir White',
'Mecole Hardman',
'David Bell',
'Joshua Palmer',
'Sterling Shepard',
'Jamaal Williams',
'Jahan Dotson',
'Brian Robinson Jr.',
'Robbie Anderson',
'Parris Campbell',
'Jeff Wilson Jr.',
'Curtis Samuel',
'Laviska Shenault Jr.',
'Donovan Peoples-Jones',
'Isaiah McKenzie',
'Myles Gaskin',
'Kendrick Bourne',
'Marvin Jones Jr.',
'KJ Hamler',
'James White',
'A.J. Green',
'Tyrion Davis-Price',
'Wan\'Dale Robinson',
'Chuba Hubbard',
'Zay Jones',
'Alec Pierce',
'Terrace Marshall Jr.',
'Braxton Berrios',
'Jerick McKinnon',
'Byron Pringle',
'Eno Benjamin',
'Marquez Callaway',
'Trey Sermon',
'Bryan Edwards',
'Isiah Pacheco',
'Rex Burkhead',
'Randall Cobb',
'Matt Breida',
'Chris Evans',
'Boston Scott',
'William Fuller V',
'Sammy Watkins',
'Samaje Perine',
'Odell Beckham Jr.',
'Joshua Kelley',
'Zack Moss',
'Mike Davis',
'Kenyan Drake',
'Kyle Philips',
'Nelson Agholor',
'John Metchie III',
'Tre\'Quan Smith',
'Damien Williams',
'Snoop Conner',
'Tyquan Thornton',
'Cedrick Wilson Jr.',
'Hassan Haskins',
'Romeo Doubs',
'Ty Johnson',
'Tyler Badie',
'DeeJay Dallas',
'Pierre Strong Jr.',
'Emmanuel Sanders',
'Cole Beasley',
'Ke\'Shawn Vaughn',
'Phillip Lindsay',
'Darius Slayton',
'Jalen Reagor',
'Ashton Dulin',
'Tutu Atwell',
'Darrynton Evans',
'Quintez Cephus',
'Laquon Treadwell',
'James Proche II',
'Josh Reynolds',
'Devin Duvernay',
'Duke Johnson Jr.',
'Dyami Brown',
'Quez Watkins',
'Kevin Harris',
'T.Y. Hilton',
'Velus Jones Jr.',
'Latavius Murray',
'Kyren Williams',
'Justin Jackson',
'Jerome Ford',
'Devontae Booker',
'Tevin Coleman',
'Devonta Freeman',
'Salvon Ahmed',
'Nick Westbrook-Ikhine',
'Giovani Bernard',
'Wayne Gallman Jr.',
'Jaret Patterson',
'Malcolm Brown',
'David Johnson']